name = "gallery"
main = "src/index.js"
compatibility_date = "2024-01-01"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "photos"
database_id = "6d117125-3892-4ece-8a34-695712436e40"

[[r2_buckets]]
binding = "R2"
bucket_name = "photos"

[assets]
directory = "dist"

[vars]
R2_DOMAIN = "https://64a7f0101c6c1c24048d6228200e3b48.r2.cloudflarestorage.com/photos"